# HTTP endpoint for querying logs / metrics
canister_query:http_request
# Canister lifecycle
canister_global_timer
canister_init
canister_post_upgrade
canister_pre_upgrade
# Exported by the `main()` function in `main.rs`; cannot be called
main
