# Timer executor endpoint added by the IC CDK
# See: https://github.com/dfinity/cdk-rs/blob/main/ic-cdk-timers/src/timer_executor.rs
canister_update:<ic-cdk internal> timer_executor
# HTTP endpoint for querying logs / metrics
canister_query:http_request
# Canister lifecycle
canister_init
canister_post_upgrade
canister_pre_upgrade
# Exported by the `main()` function in `main.rs`; cannot be called
main
